# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1228, 850)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1301, 891))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.widget = QtWidgets.QWidget(self.tab_3)
        self.widget.setGeometry(QtCore.QRect(10, 20, 801, 471))
        self.widget.setObjectName("widget")
        self.pushButton = QtWidgets.QPushButton(self.tab_3)
        self.pushButton.setGeometry(QtCore.QRect(300, 520, 191, 61))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.tab_3)
        self.label.setGeometry(QtCore.QRect(854, 50, 261, 441))
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.bg = QtWidgets.QLabel(self.tab_3)
        self.bg.setGeometry(QtCore.QRect(0, -25, 1231, 851))
        self.bg.setText("")
        self.bg.setPixmap(QtGui.QPixmap("C:/Users/Ahmed/Downloads/abstract-realistic-technology-particle-background_52683-33064.jpg"))
        self.bg.setScaledContents(True)
        self.bg.setObjectName("bg")
        self.bg.raise_()
        self.widget.raise_()
        self.pushButton.raise_()
        self.label.raise_()
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.tabWidget.addTab(self.tab_10, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(420, 480, 151, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        self.widget_7 = QtWidgets.QWidget(self.tab)
        self.widget_7.setGeometry(QtCore.QRect(190, 90, 641, 351))
        self.widget_7.setObjectName("widget_7")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab)
        self.pushButton_4.setGeometry(QtCore.QRect(420, 540, 151, 51))
        self.pushButton_4.setObjectName("pushButton_4")
        self.bg_4 = QtWidgets.QLabel(self.tab)
        self.bg_4.setGeometry(QtCore.QRect(0, 0, 1231, 851))
        self.bg_4.setText("")
        self.bg_4.setPixmap(QtGui.QPixmap("C:/Users/Ahmed/Downloads/abstract-realistic-technology-particle-background_52683-33064.jpg"))
        self.bg_4.setScaledContents(True)
        self.bg_4.setObjectName("bg_4")
        self.bg_4.raise_()
        self.pushButton_2.raise_()
        self.widget_7.raise_()
        self.pushButton_4.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.widget_2 = QtWidgets.QWidget(self.tab_4)
        self.widget_2.setGeometry(QtCore.QRect(0, 70, 571, 661))
        self.widget_2.setObjectName("widget_2")
        self.widget_3 = QtWidgets.QWidget(self.tab_4)
        self.widget_3.setGeometry(QtCore.QRect(580, 70, 661, 661))
        self.widget_3.setObjectName("widget_3")
        self.label_2 = QtWidgets.QLabel(self.tab_4)
        self.label_2.setGeometry(QtCore.QRect(140, 740, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab_4)
        self.label_3.setGeometry(QtCore.QRect(750, 740, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit.setGeometry(QtCore.QRect(490, 10, 161, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.label_4 = QtWidgets.QLabel(self.tab_4)
        self.label_4.setGeometry(QtCore.QRect(350, 20, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.bg_5 = QtWidgets.QLabel(self.tab_4)
        self.bg_5.setGeometry(QtCore.QRect(0, 0, 1231, 851))
        self.bg_5.setText("")
        self.bg_5.setPixmap(QtGui.QPixmap("C:/Users/Ahmed/Downloads/abstract-realistic-technology-particle-background_52683-33064.jpg"))
        self.bg_5.setScaledContents(True)
        self.bg_5.setObjectName("bg_5")
        self.bg_5.raise_()
        self.widget_2.raise_()
        self.widget_3.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.lineEdit.raise_()
        self.label_4.raise_()
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.widget_4 = QtWidgets.QWidget(self.tab_2)
        self.widget_4.setGeometry(QtCore.QRect(30, 80, 501, 351))
        self.widget_4.setObjectName("widget_4")
        self.widget_5 = QtWidgets.QWidget(self.tab_2)
        self.widget_5.setGeometry(QtCore.QRect(630, 80, 501, 351))
        self.widget_5.setObjectName("widget_5")
        self.widget_6 = QtWidgets.QWidget(self.tab_2)
        self.widget_6.setGeometry(QtCore.QRect(30, 490, 501, 251))
        self.widget_6.setObjectName("widget_6")
        self.widget_8 = QtWidgets.QWidget(self.tab_2)
        self.widget_8.setGeometry(QtCore.QRect(630, 490, 501, 251))
        self.widget_8.setObjectName("widget_8")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(60, 30, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(90, 450, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(710, 30, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(730, 440, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.bg_6 = QtWidgets.QLabel(self.tab_2)
        self.bg_6.setGeometry(QtCore.QRect(0, 0, 1231, 851))
        self.bg_6.setText("")
        self.bg_6.setPixmap(QtGui.QPixmap("C:/Users/Ahmed/Downloads/abstract-realistic-technology-particle-background_52683-33064.jpg"))
        self.bg_6.setScaledContents(True)
        self.bg_6.setObjectName("bg_6")
        self.bg_6.raise_()
        self.widget_4.raise_()
        self.widget_5.raise_()
        self.widget_6.raise_()
        self.widget_8.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.widget_9 = QtWidgets.QWidget(self.tab_5)
        self.widget_9.setGeometry(QtCore.QRect(20, 300, 571, 391))
        self.widget_9.setObjectName("widget_9")
        self.widget_10 = QtWidgets.QWidget(self.tab_5)
        self.widget_10.setGeometry(QtCore.QRect(630, 300, 571, 391))
        self.widget_10.setObjectName("widget_10")
        self.label_9 = QtWidgets.QLabel(self.tab_5)
        self.label_9.setGeometry(QtCore.QRect(350, 30, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab_5)
        self.label_10.setGeometry(QtCore.QRect(350, 120, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_2.setGeometry(QtCore.QRect(630, 30, 111, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_3.setGeometry(QtCore.QRect(640, 120, 161, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_3.setGeometry(QtCore.QRect(550, 210, 151, 51))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_11 = QtWidgets.QLabel(self.tab_5)
        self.label_11.setGeometry(QtCore.QRect(750, 30, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_4.setGeometry(QtCore.QRect(780, 30, 111, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.comboBox = QtWidgets.QComboBox(self.tab_5)
        self.comboBox.setGeometry(QtCore.QRect(40, 70, 141, 41))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.bg_2 = QtWidgets.QLabel(self.tab_5)
        self.bg_2.setGeometry(QtCore.QRect(0, 0, 1221, 841))
        self.bg_2.setText("")
        self.bg_2.setPixmap(QtGui.QPixmap("C:/Users/Ahmed/Downloads/abstract-realistic-technology-particle-background_52683-33064.jpg"))
        self.bg_2.setScaledContents(True)
        self.bg_2.setObjectName("bg_2")
        self.bg_2.raise_()
        self.widget_9.raise_()
        self.widget_10.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit_3.raise_()
        self.pushButton_3.raise_()
        self.label_11.raise_()
        self.lineEdit_4.raise_()
        self.comboBox.raise_()
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.widget_11 = QtWidgets.QWidget(self.tab_6)
        self.widget_11.setGeometry(QtCore.QRect(280, 10, 571, 391))
        self.widget_11.setObjectName("widget_11")
        self.widget_12 = QtWidgets.QWidget(self.tab_6)
        self.widget_12.setGeometry(QtCore.QRect(60, 470, 461, 291))
        self.widget_12.setObjectName("widget_12")
        self.widget_13 = QtWidgets.QWidget(self.tab_6)
        self.widget_13.setGeometry(QtCore.QRect(640, 470, 451, 291))
        self.widget_13.setObjectName("widget_13")
        self.label_12 = QtWidgets.QLabel(self.tab_6)
        self.label_12.setGeometry(QtCore.QRect(460, 410, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab_6)
        self.label_13.setGeometry(QtCore.QRect(150, 770, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab_6)
        self.label_14.setGeometry(QtCore.QRect(740, 780, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.bg_3 = QtWidgets.QLabel(self.tab_6)
        self.bg_3.setGeometry(QtCore.QRect(0, -20, 1221, 841))
        self.bg_3.setText("")
        self.bg_3.setPixmap(QtGui.QPixmap("C:/Users/Ahmed/Downloads/abstract-realistic-technology-particle-background_52683-33064.jpg"))
        self.bg_3.setScaledContents(True)
        self.bg_3.setObjectName("bg_3")
        self.bg_3.raise_()
        self.widget_11.raise_()
        self.widget_12.raise_()
        self.widget_13.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.bg_7 = QtWidgets.QLabel(self.tab_7)
        self.bg_7.setGeometry(QtCore.QRect(0, 0, 1231, 851))
        self.bg_7.setText("")
        self.bg_7.setPixmap(QtGui.QPixmap("C:/Users/Ahmed/Downloads/abstract-realistic-technology-particle-background_52683-33064.jpg"))
        self.bg_7.setScaledContents(True)
        self.bg_7.setObjectName("bg_7")
        self.label_15 = QtWidgets.QLabel(self.tab_7)
        self.label_15.setGeometry(QtCore.QRect(260, 40, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab_7)
        self.comboBox_2.setGeometry(QtCore.QRect(40, 30, 141, 41))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit_5.setGeometry(QtCore.QRect(520, 40, 111, 31))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.widget_14 = QtWidgets.QWidget(self.tab_7)
        self.widget_14.setGeometry(QtCore.QRect(30, 200, 571, 391))
        self.widget_14.setObjectName("widget_14")
        self.widget_15 = QtWidgets.QWidget(self.tab_7)
        self.widget_15.setGeometry(QtCore.QRect(620, 200, 571, 391))
        self.widget_15.setObjectName("widget_15")
        self.label_16 = QtWidgets.QLabel(self.tab_7)
        self.label_16.setGeometry(QtCore.QRect(230, 670, 99, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.tab_7)
        self.label_17.setGeometry(QtCore.QRect(820, 670, 99, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_5.setGeometry(QtCore.QRect(500, 120, 151, 51))
        self.pushButton_5.setObjectName("pushButton_5")
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.widget_16 = QtWidgets.QWidget(self.tab_8)
        self.widget_16.setGeometry(QtCore.QRect(30, 100, 491, 281))
        self.widget_16.setObjectName("widget_16")
        self.widget_17 = QtWidgets.QWidget(self.tab_8)
        self.widget_17.setGeometry(QtCore.QRect(40, 400, 491, 281))
        self.widget_17.setObjectName("widget_17")
        self.widget_18 = QtWidgets.QWidget(self.tab_8)
        self.widget_18.setGeometry(QtCore.QRect(690, 400, 491, 281))
        self.widget_18.setObjectName("widget_18")
        self.label_18 = QtWidgets.QLabel(self.tab_8)
        self.label_18.setGeometry(QtCore.QRect(150, 690, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.tab_8)
        self.label_19.setGeometry(QtCore.QRect(780, 690, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.tab_8)
        self.label_20.setGeometry(QtCore.QRect(440, 730, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.tab_8)
        self.label_21.setGeometry(QtCore.QRect(420, 770, 401, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.widget_25 = QtWidgets.QWidget(self.tab_8)
        self.widget_25.setGeometry(QtCore.QRect(690, 100, 491, 281))
        self.widget_25.setObjectName("widget_25")
        self.columnView = QtWidgets.QColumnView(self.tab_8)
        self.columnView.setGeometry(QtCore.QRect(10, 10, 571, 41))
        self.columnView.setObjectName("columnView")
        self.columnView_2 = QtWidgets.QColumnView(self.tab_8)
        self.columnView_2.setGeometry(QtCore.QRect(630, 10, 581, 41))
        self.columnView_2.setObjectName("columnView_2")
        self.checkBox = QtWidgets.QCheckBox(self.tab_8)
        self.checkBox.setGeometry(QtCore.QRect(20, 20, 81, 20))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.tab_8)
        self.checkBox_2.setGeometry(QtCore.QRect(110, 20, 91, 20))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.tab_8)
        self.checkBox_3.setGeometry(QtCore.QRect(210, 20, 81, 20))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.tab_8)
        self.checkBox_4.setGeometry(QtCore.QRect(290, 20, 81, 20))
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.tab_8)
        self.checkBox_5.setGeometry(QtCore.QRect(390, 20, 81, 20))
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.tab_8)
        self.checkBox_6.setGeometry(QtCore.QRect(470, 20, 111, 20))
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_7 = QtWidgets.QCheckBox(self.tab_8)
        self.checkBox_7.setGeometry(QtCore.QRect(1020, 20, 81, 20))
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(self.tab_8)
        self.checkBox_8.setGeometry(QtCore.QRect(920, 20, 81, 20))
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_9 = QtWidgets.QCheckBox(self.tab_8)
        self.checkBox_9.setGeometry(QtCore.QRect(1110, 20, 101, 20))
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_10 = QtWidgets.QCheckBox(self.tab_8)
        self.checkBox_10.setGeometry(QtCore.QRect(640, 20, 81, 20))
        self.checkBox_10.setObjectName("checkBox_10")
        self.checkBox_11 = QtWidgets.QCheckBox(self.tab_8)
        self.checkBox_11.setGeometry(QtCore.QRect(790, 20, 121, 20))
        self.checkBox_11.setObjectName("checkBox_11")
        self.checkBox_12 = QtWidgets.QCheckBox(self.tab_8)
        self.checkBox_12.setGeometry(QtCore.QRect(700, 20, 91, 20))
        self.checkBox_12.setObjectName("checkBox_12")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_8)
        self.pushButton_6.setGeometry(QtCore.QRect(840, 60, 151, 31))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_8)
        self.pushButton_7.setGeometry(QtCore.QRect(200, 60, 151, 31))
        self.pushButton_7.setObjectName("pushButton_7")
        self.bg_8 = QtWidgets.QLabel(self.tab_8)
        self.bg_8.setGeometry(QtCore.QRect(0, 0, 1231, 851))
        self.bg_8.setText("")
        self.bg_8.setPixmap(QtGui.QPixmap("C:/Users/Ahmed/Downloads/abstract-realistic-technology-particle-background_52683-33064.jpg"))
        self.bg_8.setScaledContents(True)
        self.bg_8.setObjectName("bg_8")
        self.bg_8.raise_()
        self.widget_16.raise_()
        self.widget_17.raise_()
        self.widget_18.raise_()
        self.label_18.raise_()
        self.label_19.raise_()
        self.label_20.raise_()
        self.label_21.raise_()
        self.widget_25.raise_()
        self.columnView.raise_()
        self.columnView_2.raise_()
        self.checkBox.raise_()
        self.checkBox_2.raise_()
        self.checkBox_3.raise_()
        self.checkBox_4.raise_()
        self.checkBox_5.raise_()
        self.checkBox_6.raise_()
        self.checkBox_7.raise_()
        self.checkBox_8.raise_()
        self.checkBox_9.raise_()
        self.checkBox_10.raise_()
        self.checkBox_11.raise_()
        self.checkBox_12.raise_()
        self.pushButton_6.raise_()
        self.pushButton_7.raise_()
        self.tabWidget.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.widget_19 = QtWidgets.QWidget(self.tab_9)
        self.widget_19.setGeometry(QtCore.QRect(10, 20, 371, 281))
        self.widget_19.setObjectName("widget_19")
        self.widget_20 = QtWidgets.QWidget(self.tab_9)
        self.widget_20.setGeometry(QtCore.QRect(400, 20, 391, 281))
        self.widget_20.setObjectName("widget_20")
        self.widget_21 = QtWidgets.QWidget(self.tab_9)
        self.widget_21.setGeometry(QtCore.QRect(820, 20, 391, 281))
        self.widget_21.setObjectName("widget_21")
        self.widget_22 = QtWidgets.QWidget(self.tab_9)
        self.widget_22.setGeometry(QtCore.QRect(0, 420, 391, 281))
        self.widget_22.setObjectName("widget_22")
        self.widget_23 = QtWidgets.QWidget(self.tab_9)
        self.widget_23.setGeometry(QtCore.QRect(400, 420, 391, 281))
        self.widget_23.setObjectName("widget_23")
        self.widget_24 = QtWidgets.QWidget(self.tab_9)
        self.widget_24.setGeometry(QtCore.QRect(810, 420, 391, 281))
        self.widget_24.setObjectName("widget_24")
        self.label_22 = QtWidgets.QLabel(self.tab_9)
        self.label_22.setGeometry(QtCore.QRect(40, 340, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.tab_9)
        self.label_23.setGeometry(QtCore.QRect(450, 340, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.tab_9)
        self.label_24.setGeometry(QtCore.QRect(880, 340, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.tab_9)
        self.label_25.setGeometry(QtCore.QRect(50, 720, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.tab_9)
        self.label_26.setGeometry(QtCore.QRect(460, 730, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.tab_9)
        self.label_27.setGeometry(QtCore.QRect(870, 730, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.bg_9 = QtWidgets.QLabel(self.tab_9)
        self.bg_9.setGeometry(QtCore.QRect(0, -20, 1231, 851))
        self.bg_9.setText("")
        self.bg_9.setPixmap(QtGui.QPixmap("C:/Users/Ahmed/Downloads/abstract-realistic-technology-particle-background_52683-33064.jpg"))
        self.bg_9.setScaledContents(True)
        self.bg_9.setObjectName("bg_9")
        self.bg_9.raise_()
        self.widget_19.raise_()
        self.widget_20.raise_()
        self.widget_21.raise_()
        self.widget_22.raise_()
        self.widget_23.raise_()
        self.widget_24.raise_()
        self.label_22.raise_()
        self.label_23.raise_()
        self.label_24.raise_()
        self.label_25.raise_()
        self.label_26.raise_()
        self.label_27.raise_()
        self.tabWidget.addTab(self.tab_9, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.widget_26 = QtWidgets.QWidget(self.tab_11)
        self.widget_26.setGeometry(QtCore.QRect(40, 20, 491, 381))
        self.widget_26.setObjectName("widget_26")
        self.widget_27 = QtWidgets.QWidget(self.tab_11)
        self.widget_27.setGeometry(QtCore.QRect(40, 420, 491, 381))
        self.widget_27.setObjectName("widget_27")
        self.widget_28 = QtWidgets.QWidget(self.tab_11)
        self.widget_28.setGeometry(QtCore.QRect(650, 210, 491, 381))
        self.widget_28.setObjectName("widget_28")
        self.bg_10 = QtWidgets.QLabel(self.tab_11)
        self.bg_10.setGeometry(QtCore.QRect(0, 0, 1231, 851))
        self.bg_10.setText("")
        self.bg_10.setPixmap(QtGui.QPixmap("C:/Users/Ahmed/Downloads/abstract-realistic-technology-particle-background_52683-33064.jpg"))
        self.bg_10.setScaledContents(True)
        self.bg_10.setObjectName("bg_10")
        self.bg_10.raise_()
        self.widget_26.raise_()
        self.widget_27.raise_()
        self.widget_28.raise_()
        self.tabWidget.addTab(self.tab_11, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(10)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Image Processing"))
        self.pushButton.setText(_translate("Form", "Browse"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "Display"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_10), _translate("Form", "Page"))
        self.pushButton_2.setText(_translate("Form", "Task 1.5"))
        self.pushButton_4.setText(_translate("Form", "Undo"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Task 1.5"))
        self.label_2.setText(_translate("Form", "Bilinear Interpolation"))
        self.label_3.setText(_translate("Form", "Nearest Neighbor Interpolation"))
        self.label_4.setText(_translate("Form", "Zoom Factor:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "Interpolation"))
        self.label_5.setText(_translate("Form", "Unequalized Image"))
        self.label_6.setText(_translate("Form", "Unequalized Histogram"))
        self.label_7.setText(_translate("Form", "Equalized Image"))
        self.label_8.setText(_translate("Form", "Equalized Histogram"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Histogram"))
        self.label_9.setText(_translate("Form", "Kernel Size"))
        self.label_10.setText(_translate("Form", "Factor"))
        self.pushButton_3.setText(_translate("Form", "Filter"))
        self.label_11.setText(_translate("Form", "x"))
        self.comboBox.setItemText(0, _translate("Form", "Choose Padding"))
        self.comboBox.setItemText(1, _translate("Form", "Zero"))
        self.comboBox.setItemText(2, _translate("Form", "Mirror"))
        self.comboBox.setItemText(3, _translate("Form", "Replicate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Form", "Spatial Filter"))
        self.label_12.setText(_translate("Form", "Original Image"))
        self.label_13.setText(_translate("Form", "Magnitude"))
        self.label_14.setText(_translate("Form", "Phase"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("Form", "Fourier"))
        self.label_15.setText(_translate("Form", "Kernel Size"))
        self.comboBox_2.setItemText(0, _translate("Form", "Choose Padding"))
        self.comboBox_2.setItemText(1, _translate("Form", "Zero"))
        self.comboBox_2.setItemText(2, _translate("Form", "Mirror"))
        self.comboBox_2.setItemText(3, _translate("Form", "Replicate"))
        self.label_16.setText(_translate("Form", "After IFFT"))
        self.label_17.setText(_translate("Form", "Difference"))
        self.pushButton_5.setText(_translate("Form", "Filter"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("Form", "Fourier Filtering"))
        self.label_18.setText(_translate("Form", "ROI"))
        self.label_19.setText(_translate("Form", "ROI Histogram"))
        self.label_20.setText(_translate("Form", "ROI MEAN: "))
        self.label_21.setText(_translate("Form", "ROI Standard Deviation: "))
        self.checkBox.setText(_translate("Form", "gaussian"))
        self.checkBox_2.setText(_translate("Form", "exponential"))
        self.checkBox_3.setText(_translate("Form", "gamma"))
        self.checkBox_4.setText(_translate("Form", "rayleigh"))
        self.checkBox_5.setText(_translate("Form", "uniform"))
        self.checkBox_6.setText(_translate("Form", "salt_n_pepper"))
        self.checkBox_7.setText(_translate("Form", "Adaptive"))
        self.checkBox_8.setText(_translate("Form", "Geometric"))
        self.checkBox_9.setText(_translate("Form", "Median"))
        self.checkBox_10.setText(_translate("Form", "Mean"))
        self.checkBox_11.setText(_translate("Form", "Contraharmonic"))
        self.checkBox_12.setText(_translate("Form", "Harmonic"))
        self.pushButton_6.setText(_translate("Form", "Filter"))
        self.pushButton_7.setText(_translate("Form", "Noise"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("Form", "Noise"))
        self.label_22.setText(_translate("Form", "Shepp-Logan Phantom"))
        self.label_23.setText(_translate("Form", "Sinogram of Phantom"))
        self.label_24.setText(_translate("Form", "Laminogram 1 - No filter"))
        self.label_25.setText(_translate("Form", "Laminogram 2 - No filter"))
        self.label_26.setText(_translate("Form", "Laminogram 3 - Ram-Lak"))
        self.label_27.setText(_translate("Form", "Laminogram 4 - Hamming"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), _translate("Form", "Back Projection"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_11), _translate("Form", "Color Mapss"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

